/* CRM: kanban nativo e detalhe consolidado de cada negociação. */
(() => {
  const app = document.getElementById('crmApp');
  if (!app || !window.SevApi || !window.SevAuth) return;
  const state = { stages: [], detail: null, detailTab: 'history' };
  const money = cents => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format((Number(cents) || 0) / 100);
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
  const dateLabel = value => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`)) : 'Sem prazo';
  const dateTimeLabel = value => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
  const status = (message, error = false) => { const element = app.querySelector('[data-crm-status]'); if (element) { element.textContent = message; element.classList.toggle('error', error); } };
  const loadKanban = async () => { state.stages = await window.SevApi.getCrmKanban(); renderKanban(); };

  const renderKanban = () => {
    app.innerHTML = `<section class="crm-toolbar"><div><h2>Funil de negociações</h2><p>Arraste os cards entre as etapas para atualizar o andamento.</p></div><button class="primary-button" type="button" data-new-negotiation>Nova negociação</button></section><p class="evaluation-status" data-crm-status role="status"></p><section class="crm-board">${state.stages.map(stage => `<article class="crm-column" data-stage-drop="${stage.id}"><header><span class="crm-stage-color" style="background:${escapeHtml(stage.color)}"></span><div><strong>${escapeHtml(stage.name)}</strong><small>${stage.negotiations.length} oportunidade${stage.negotiations.length === 1 ? '' : 's'} · ${money(stage.totalCents)}</small></div></header><div class="crm-cards">${stage.negotiations.map(deal => `<button class="crm-card" type="button" draggable="true" data-deal-id="${deal.id}" data-open-negotiation="${deal.id}"><strong>${escapeHtml(deal.name)}</strong><span>${money(deal.valueCents)}</span>${deal.responsibleName ? `<small>${escapeHtml(deal.responsibleName)}</small>` : ''}${deal.source ? `<small>${escapeHtml(deal.source)}</small>` : ''}</button>`).join('') || '<p class="crm-column-empty">Nenhuma negociação</p>'}</div></article>`).join('')}</section>`;
    app.querySelectorAll('[data-deal-id]').forEach(card => card.addEventListener('dragstart', event => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', card.dataset.dealId); card.classList.add('is-dragging'); }));
    app.querySelectorAll('[data-deal-id]').forEach(card => card.addEventListener('dragend', () => card.classList.remove('is-dragging')));
    app.querySelectorAll('[data-stage-drop]').forEach(column => {
      column.addEventListener('dragover', event => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; column.classList.add('is-drag-over'); });
      column.addEventListener('dragleave', () => column.classList.remove('is-drag-over'));
      column.addEventListener('drop', async event => { event.preventDefault(); column.classList.remove('is-drag-over'); const id = event.dataTransfer.getData('text/plain'); if (!id) return; status('Movendo negociação…'); try { await window.SevApi.moveCrmNegotiation(id, column.dataset.stageDrop); await loadKanban(); } catch (error) { status(error.message || 'Não foi possível mover a negociação.', true); } });
    });
  };

  const renderNewNegotiation = () => {
    app.innerHTML = `<section class="crm-detail-head"><button class="back-link" type="button" data-back-kanban>← Voltar ao funil</button><h2>Nova negociação</h2><p>Registre a oportunidade inicial e acompanhe a evolução pelo funil.</p></section><form class="crm-form" id="crmNewForm"><label class="field"><span>Nome da negociação</span><input name="name" required minlength="2" maxlength="160" placeholder="Ex.: Projeto de implantação"></label><label class="field"><span>Etapa</span><select name="stageId">${state.stages.map(stage => `<option value="${stage.id}">${escapeHtml(stage.name)}</option>`).join('')}</select></label><label class="field"><span>Valor estimado (R$)</span><input name="value" type="number" min="0" step="0.01" value="0"></label><label class="field"><span>Fonte</span><input name="source" maxlength="100" placeholder="Ex.: Indicação"></label><label class="field"><span>Campanha</span><input name="campaign" maxlength="140"></label><label class="field crm-form-full"><span>Qualificação</span><textarea name="qualification" maxlength="240" placeholder="Contexto, necessidade e próximos passos"></textarea></label><div class="evaluation-editor-actions crm-form-full"><p class="evaluation-status" data-crm-status role="status"></p><button class="primary-button" type="submit">Criar negociação</button></div></form>`;
    document.getElementById('crmNewForm').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; const value = Math.round(Number(form.elements.value.value || 0) * 100); const submit = form.querySelector('button[type="submit"]'); submit.disabled = true; status('Criando negociação…'); try { const result = await window.SevApi.createCrmNegotiation({ etapaId: form.elements.stageId.value, nome: form.elements.name.value.trim(), valorCents: value, fonte: form.elements.source.value.trim(), campanha: form.elements.campaign.value.trim(), qualificacao: form.elements.qualification.value.trim() }); await openDetail(result.negotiation.id); } catch (error) { status(error.message || 'Não foi possível criar a negociação.', true); submit.disabled = false; } });
  };

  const renderDetail = () => {
    const detail = state.detail.negotiation;
    const pending = detail.tasks.filter(task => !task.done);
    const tabContent = state.detailTab === 'history'
      ? `<div class="crm-timeline">${detail.history.length ? detail.history.map(item => `<article><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.description || '')}</span><small>${escapeHtml(item.createdByName || 'Sistema')} · ${dateTimeLabel(item.createdAt)}</small></article>`).join('') : '<p class="crm-column-empty">Ainda não há movimentações.</p>'}</div><form id="crmHistoryForm" class="crm-inline-form"><input name="title" required maxlength="160" placeholder="Adicionar observação"><button class="secondary-button" type="submit">Registrar</button></form>`
      : `<div class="crm-proposal-summary"><strong>Total da proposta</strong><span>${money(detail.proposalTotalCents)}</span></div><div class="crm-proposal-list">${detail.proposalItems.length ? detail.proposalItems.map(item => `<div><span><strong>${escapeHtml(item.productName)}</strong><small>${item.quantity} × ${money(item.priceCents)}</small></span><span>${money(item.totalCents)} <button class="icon-text-button" type="button" data-delete-proposal="${item.id}" aria-label="Remover item">×</button></span></div>`).join('') : '<p class="crm-column-empty">Nenhum item de proposta.</p>'}</div><form id="crmProposalForm" class="crm-proposal-form"><input name="name" required maxlength="160" placeholder="Produto ou serviço"><input name="quantity" type="number" min="1" value="1" required><input name="price" type="number" min="0" step="0.01" value="0" required><button class="secondary-button" type="submit">Adicionar item</button></form>`;
    app.innerHTML = `<section class="crm-detail-head"><button class="back-link" type="button" data-back-kanban>← Voltar ao funil</button><div class="crm-detail-title"><div><p class="eyebrow" style="color:${escapeHtml(detail.stage.color)}">${escapeHtml(detail.stage.name)}</p><h2>${escapeHtml(detail.name)}</h2><p>${money(detail.valueCents)} · ${escapeHtml(detail.source || 'Sem fonte')}${detail.campaign ? ` · ${escapeHtml(detail.campaign)}` : ''}</p></div><button class="secondary-button" type="button" data-edit-negotiation>Editar</button></div></section><section class="crm-detail-grid"><article class="crm-info-card"><h3>Dados da negociação</h3><dl><div><dt>Responsável</dt><dd>${escapeHtml(detail.responsibleName || 'Não definido')}</dd></div><div><dt>Qualificação</dt><dd>${escapeHtml(detail.qualification || 'Sem observações')}</dd></div><div><dt>Criada em</dt><dd>${dateTimeLabel(detail.createdAt)}</dd></div></dl></article><article class="crm-tasks-card"><div class="crm-section-head"><h3>Tarefas pendentes</h3><span>${pending.length}</span></div><div class="crm-task-list">${detail.tasks.length ? detail.tasks.map(task => `<label class="crm-task ${task.done ? 'is-done' : ''}"><input type="checkbox" data-task-toggle="${task.id}" ${task.done ? 'checked' : ''}><span>${escapeHtml(task.text)}<small>${dateLabel(task.dueDate)}</small></span></label>`).join('') : '<p class="crm-column-empty">Nenhuma tarefa cadastrada.</p>'}</div><form id="crmTaskForm" class="crm-inline-form"><input name="text" required maxlength="500" placeholder="Nova tarefa"><input name="dueDate" type="date"><button class="secondary-button" type="submit">Adicionar</button></form></article></section><section class="crm-tabs"><button type="button" class="${state.detailTab === 'history' ? 'active' : ''}" data-crm-tab="history">Histórico</button><button type="button" class="${state.detailTab === 'proposal' ? 'active' : ''}" data-crm-tab="proposal">Produtos e propostas</button></section><section class="crm-detail-panel">${tabContent}</section>`;
    bindDetailForms(detail.id);
  };
  const bindDetailForms = id => {
    document.getElementById('crmTaskForm')?.addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; try { await window.SevApi.createCrmTask(id, { texto: form.elements.text.value.trim(), prazo: form.elements.dueDate.value || null }); await openDetail(id); } catch (error) { status(error.message || 'Não foi possível criar a tarefa.', true); } });
    document.getElementById('crmProposalForm')?.addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; try { await window.SevApi.createCrmProposalItem(id, { nomeProduto: form.elements.name.value.trim(), quantidade: Number(form.elements.quantity.value), precoCents: Math.round(Number(form.elements.price.value) * 100) }); await openDetail(id); } catch (error) { status(error.message || 'Não foi possível adicionar o item.', true); } });
    document.getElementById('crmHistoryForm')?.addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; try { await window.SevApi.createCrmHistory(id, { titulo: form.elements.title.value.trim() }); await openDetail(id); } catch (error) { status(error.message || 'Não foi possível registrar a observação.', true); } });
  };
  const openDetail = async id => { app.innerHTML = '<p class="module-loading">Carregando negociação…</p>'; try { state.detail = await window.SevApi.getCrmNegotiation(id); renderDetail(); } catch (error) { await loadKanban(); status(error.message || 'Não foi possível carregar a negociação.', true); } };
  const renderEdit = () => { const deal = state.detail.negotiation; app.innerHTML = `<section class="crm-detail-head"><button class="back-link" type="button" data-open-negotiation="${deal.id}">← Voltar aos detalhes</button><h2>Editar negociação</h2></section><form class="crm-form" id="crmEditForm"><label class="field"><span>Nome</span><input name="name" minlength="2" maxlength="160" required value="${escapeHtml(deal.name)}"></label><label class="field"><span>Valor estimado (R$)</span><input name="value" type="number" min="0" step="0.01" value="${deal.valueCents / 100}"></label><label class="field"><span>Fonte</span><input name="source" maxlength="100" value="${escapeHtml(deal.source || '')}"></label><label class="field"><span>Campanha</span><input name="campaign" maxlength="140" value="${escapeHtml(deal.campaign || '')}"></label><label class="field crm-form-full"><span>Qualificação</span><textarea name="qualification" maxlength="240">${escapeHtml(deal.qualification || '')}</textarea></label><div class="evaluation-editor-actions crm-form-full"><p class="evaluation-status" data-crm-status role="status"></p><button class="primary-button" type="submit">Salvar alterações</button></div></form>`; document.getElementById('crmEditForm').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; try { await window.SevApi.updateCrmNegotiation(deal.id, { nome: form.elements.name.value.trim(), valorCents: Math.round(Number(form.elements.value.value) * 100), fonte: form.elements.source.value.trim(), campanha: form.elements.campaign.value.trim(), qualificacao: form.elements.qualification.value.trim() }); await openDetail(deal.id); } catch (error) { status(error.message || 'Não foi possível atualizar a negociação.', true); } }); };

  app.addEventListener('click', async event => {
    const button = event.target.closest('button');
    if (button?.dataset.newNegotiation !== undefined) return renderNewNegotiation();
    if (button?.dataset.backKanban !== undefined) return loadKanban().catch(error => status(error.message, true));
    if (button?.dataset.openNegotiation) return openDetail(button.dataset.openNegotiation);
    if (button?.dataset.editNegotiation !== undefined) return renderEdit();
    if (button?.dataset.crmTab) { state.detailTab = button.dataset.crmTab; return renderDetail(); }
    if (button?.dataset.deleteProposal) { try { await window.SevApi.deleteCrmProposalItem(button.dataset.deleteProposal); await openDetail(state.detail.negotiation.id); } catch (error) { status(error.message || 'Não foi possível remover o item.', true); } }
  });
  app.addEventListener('change', async event => { const checkbox = event.target.closest('[data-task-toggle]'); if (!checkbox) return; try { await window.SevApi.updateCrmTask(checkbox.dataset.taskToggle, { feita: checkbox.checked }); await openDetail(state.detail.negotiation.id); } catch (error) { checkbox.checked = !checkbox.checked; status(error.message || 'Não foi possível atualizar a tarefa.', true); } });
  window.SevAuth.ready.then(async user => { if (!user) return; try { await loadKanban(); } catch (error) { app.innerHTML = `<p class="evaluation-status error">${escapeHtml(error.message || 'Não foi possível carregar o CRM.')}</p>`; } });
})();
